"""Pydantic models for task plans and execution state."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from enum import StrEnum

from pydantic import BaseModel, Field

from models.capabilities import RiskLevel


class StepStatus(StrEnum):
    """Status of an individual step within a task plan."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    AWAITING_APPROVAL = "awaiting_approval"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class TaskStatus(StrEnum):
    """Overall status of a task plan."""

    PLANNING = "planning"
    EXECUTING = "executing"
    PAUSED = "paused"  # waiting for HITL approval
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class TaskStep(BaseModel):
    """A single step in a multi-step task plan."""

    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:8])
    tool_name: str  # which tool to invoke (e.g. "web_search", "os_write_file")
    description: str  # human-readable description of what this step does
    parameters: dict = Field(default_factory=dict)
    status: StepStatus = StepStatus.PENDING
    result: str = ""
    error: str = ""
    is_destructive: bool = False  # triggers HITL approval gate
    domain: str = "general"
    risk_level: RiskLevel = RiskLevel.MEDIUM
    requires_admin: bool = False
    requires_dry_run: bool = False
    requires_backup: bool = False
    requires_double_confirmation: bool = False
    dry_run_done: bool = False
    backup_ready: bool = False
    admin_verified: bool = False
    retry_count: int = 0
    max_retries: int = 2


class TaskPlan(BaseModel):
    """A decomposed multi-step plan generated by the Cognitive Router."""

    id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    user_request: str  # the original natural-language request
    steps: list[TaskStep] = Field(default_factory=list)
    status: TaskStatus = TaskStatus.PLANNING
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    completed_at: datetime | None = None
    error_summary: str = ""

    @property
    def current_step(self) -> TaskStep | None:
        """Return the first non-completed step, or None if all done."""
        for step in self.steps:
            if step.status in (
                StepStatus.PENDING,
                StepStatus.IN_PROGRESS,
                StepStatus.AWAITING_APPROVAL,
            ):
                return step
        return None

    @property
    def is_complete(self) -> bool:
        return all(s.status in (StepStatus.COMPLETED, StepStatus.SKIPPED) for s in self.steps)

    def mark_complete(self) -> None:
        """Mark the plan as completed."""
        self.status = TaskStatus.COMPLETED
        self.completed_at = datetime.now(UTC)

    def mark_failed(self, error: str) -> None:
        """Mark the plan as failed with an error summary."""
        self.status = TaskStatus.FAILED
        self.error_summary = error
        self.completed_at = datetime.now(UTC)
